services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: api
    restart: unless-stopped
    user: node

  nginx:
    image: nginx:latest
    ports:
      - '5000:5000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: homework
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: postgres
